---
name: build all
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          [
            dotnetsdk5.0-alpine,
            node14-bullseye
          ]
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.7.0
        with:
          context: ./builder/${{ matrix.images }}
          push: true
          tags: |
            shinomineko/builder:${{ matrix.images }}
