---
name: build all

on:
  schedule:
    - cron: "0 0 * * 0"

  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "::set-output name=date::$(date +'%Y%m%d')"
        id: date

      - uses: docker/build-push-action@v2.5.0
        with:
          file: ./dotnet/sdk/Dockerfile
          push: true
          tags: |
            shinomineko/builder:dotnet-sdk-3.1-${{ steps.date.outputs.date }}
            shinomineko/builder:dotnet-sdk-3.1-latest
